INSERT INTO public.series (anilist_id, slug, title, alt_titles, synopsis, cover_url, banner_url, kind, status, author, artist, genres, rating, views, published, pinned) VALUES
(105778, 'chainsaw-man', 'Chainsaw Man', 'Chainsaw Man, チェンソーマン', 'The name says it all! Denji''s life of poverty is changed forever when he merges with his pet chainsaw dog, Pochita! Now he''s living in the big city and an official Devil Hunter.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx105778-euxXZEIfDY2u.png', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/105778-ppHaMwown6c9.jpg', 'Manga', 'Completo', 'Tatsuki Fujimoto', 'Tatsuki Fujimoto', ARRAY['Action','Comedy','Drama','Horror','Supernatural']::text[], 8.4, 6676, true, true),
(105398, 'na-honjaman-level-up', 'Na Honjaman Level Up', 'Solo Leveling, 나 혼자만 레벨업', 'Em um mundo onde caçadores despertos enfrentam monstros mortais, Seong Jin-U, o caçador mais fraco da humanidade, recebe a chance de evoluir sem limites.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx105398-b673Vt5ZSuz3.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/105398-4UrEhdqZukrg.jpg', 'Manhwa', 'Completo', 'So-Ryeong Gi', 'Seong-Rak Jang', ARRAY['Action','Adventure','Fantasy']::text[], 8.4, 6203, true, true),
(101517, 'jujutsu-kaisen', 'Jujutsu Kaisen', 'Jujutsu Kaisen, 呪術廻戦', 'Yuji Itadori parece um adolescente comum, mas sua força física impressiona. Tudo muda quando o Clube de Ocultismo desperta uma maldição poderosa.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx101517-H3TdM3g5ZUe9.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/101517-FrJtb3Th3HtF.jpg', 'Manga', 'Completo', 'Gege Akutami', 'Gege Akutami', ARRAY['Action','Drama','Supernatural']::text[], 8.0, 5730, true, true),
(30002, 'berserk', 'Berserk', 'Berserk, ベルセルク', 'Guts, o Espadachim Negro, carrega uma espada gigantesca, uma mão de ferro e as marcas de inúmeras batalhas.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30002-Cul4OeN7bYtn.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/30002-3TuoSMl20fUX.jpg', 'Manga', 'Em andamento', 'Kentarou Miura', 'Kentarou Miura', ARRAY['Action','Adventure','Drama','Fantasy','Horror','Psychological']::text[], 9.2, 5257, true, false),
(30013, 'one-piece', 'ONE PIECE', 'One Piece, ONE PIECE', 'Monkey D. Luffy sonha em ser o Rei dos Piratas depois de ganhar poderes elásticos ao comer uma Akuma no Mi.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30013-BeslEMqiPhlk.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/30013-hbbRZqC5MjYh.jpg', 'Manga', 'Em andamento', 'Eiichirou Oda', 'Eiichirou Oda', ARRAY['Action','Adventure','Comedy','Fantasy']::text[], 9.1, 4784, true, false),
(53390, 'shingeki-no-kyojin', 'Shingeki no Kyojin', 'Attack on Titan, 進撃の巨人', 'A humanidade vive cercada por muralhas para escapar dos Titãs, gigantes que devoram pessoas sem explicação.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx53390-1RsuABC34P9D.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/53390-6Uru5rrjh8zv.jpg', 'Manga', 'Completo', 'Hajime Isayama', 'Hajime Isayama', ARRAY['Action','Drama','Fantasy','Mystery']::text[], 8.4, 4311, true, false),
(87216, 'kimetsu-no-yaiba', 'Kimetsu no Yaiba', 'Demon Slayer, 鬼滅の刃', 'Tanjirou vivia em paz vendendo carvão até que demônios massacraram sua família e transformaram sua irmã Nezuko.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx87216-c9bSNVD10UuD.png', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/87216-TVKEGfSxAqKs.jpg', 'Manga', 'Completo', 'Koyoharu Gotouge', 'Koyoharu Gotouge', ARRAY['Action','Adventure','Drama','Supernatural']::text[], 7.9, 3838, true, false),
(63327, 'tokyo-ghoul', 'Tokyo Ghoul', 'Tokyo Ghoul, 東京喰種', 'Ken Kaneki se torna o primeiro híbrido meio humano meio ghoul e precisa aprender a viver entre dois mundos.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx63327-glC9cDxYBja9.png', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/63327-uaFaG1HAJ0tK.jpg', 'Manga', 'Completo', 'Sui Ishida', 'Sui Ishida', ARRAY['Action','Horror','Mystery','Psychological','Supernatural']::text[], 8.4, 3365, true, false),
(34632, 'oyasumi-punpun', 'Oyasumi Punpun', 'Goodnight Punpun, おやすみプンプン', 'A vida de Punpun Punyama em uma cidade comum, entre sonhos grandiosos e a dureza de crescer.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx34632-5xMDkx3pXsEh.png', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/34632-JULTgA6q6jAH.jpg', 'Manga', 'Completo', 'Inio Asano', 'Inio Asano', ARRAY['Drama','Psychological','Slice of Life']::text[], 8.8, 2892, true, false),
(85486, 'boku-no-hero-academia', 'Boku no Hero Academia', 'My Hero Academia, 僕のヒーローアカデミア', 'Izuku Midoriya quer ser herói mais que tudo, mesmo sem nenhum poder — até conhecer o maior herói do mundo.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx85486-INqnYx8gL3eX.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/85486-4mTRih1qOdgk.jpg', 'Manga', 'Completo', 'Kouhei Horikoshi', 'Kouhei Horikoshi', ARRAY['Action','Adventure','Comedy','Drama','Fantasy']::text[], 7.8, 2419, true, false),
(74347, 'one-punch-man', 'One Punch-Man', 'One-Punch Man, ワンパンマン', 'Saitama parece totalmente comum, mas resolve qualquer luta com um único soco — e isso é um problema.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx74347-sZpmNJ5xLwRK.jpg', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/74347-xAQI9BxcpWM3.jpg', 'Manga', 'Em andamento', 'ONE', 'Yuusuke Murata', ARRAY['Action','Comedy','Sci-Fi','Supernatural']::text[], 8.5, 1946, true, false),
(30656, 'vagabond', 'Vagabond', 'Vagabond, バガボンド', 'Aos dezessete anos, Shinmen Takezo inicia sua jornada pela via da espada após a batalha de Sekigahara.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30656-9mW113O7rDnA.png', 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/30656-XYzvRlsc3iK4.jpg', 'Manga', 'Em andamento', 'Takehiko Inoue', 'Takehiko Inoue', ARRAY['Action','Adventure','Drama']::text[], 9.1, 1473, true, false)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.chapters (series_id, number, title, pages, created_at)
SELECT s.id, n.num, NULL,
  to_jsonb(ARRAY[s.banner_url, s.cover_url, s.banner_url]),
  now() - (n.num || ' hours')::interval
FROM public.series s
CROSS JOIN (VALUES (1), (2), (3)) AS n(num)
WHERE s.slug IN ('chainsaw-man','na-honjaman-level-up','jujutsu-kaisen','berserk','one-piece','shingeki-no-kyojin')
ON CONFLICT (series_id, number) DO NOTHING;