/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RankingLeitoresRouteImport } from './routes/ranking-leitores'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as ListasIndexRouteImport } from './routes/listas/index'
import { Route as ListasIdRouteImport } from './routes/listas/$id'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin/$id'
import { Route as AuthenticatedAdminContasRouteImport } from './routes/_authenticated/admin/contas'
import { Route as AuthenticatedAdminMoldurasRouteImport } from './routes/_authenticated/admin/molduras'
import { Route as AuthenticatedAdminNovaRouteImport } from './routes/_authenticated/admin/nova'
import { Route as AuthenticatedAdminNovelsRouteImport } from './routes/_authenticated/admin/novels'
import { Route as AuthenticatedAdminObrasRouteImport } from './routes/_authenticated/admin/obras'
import { Route as AuthenticatedAdminSelosRouteImport } from './routes/_authenticated/admin/selos'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin/suporte'
import { Route as ObraSlugIndexRouteImport } from './routes/obra/$slug/index'
import { Route as ObraSlugChapterRouteImport } from './routes/obra/$slug/$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingLeitoresRoute = RankingLeitoresRouteImport.update({
  id: '/ranking-leitores',
  path: '/ranking-leitores',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ListasIndexRoute = ListasIndexRouteImport.update({
  id: '/listas/',
  path: '/listas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasIdRoute = ListasIdRouteImport.update({
  id: '/listas/$id',
  path: '/listas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminContasRoute =
  AuthenticatedAdminContasRouteImport.update({
    id: '/admin/contas',
    path: '/admin/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMoldurasRoute =
  AuthenticatedAdminMoldurasRouteImport.update({
    id: '/admin/molduras',
    path: '/admin/molduras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNovaRoute = AuthenticatedAdminNovaRouteImport.update({
  id: '/admin/nova',
  path: '/admin/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNovelsRoute =
  AuthenticatedAdminNovelsRouteImport.update({
    id: '/admin/novels',
    path: '/admin/novels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminObrasRoute = AuthenticatedAdminObrasRouteImport.update({
  id: '/admin/obras',
  path: '/admin/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSelosRoute = AuthenticatedAdminSelosRouteImport.update({
  id: '/admin/selos',
  path: '/admin/selos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/admin/suporte',
    path: '/admin/suporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ObraSlugIndexRoute = ObraSlugIndexRouteImport.update({
  id: '/obra/$slug/',
  path: '/obra/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraSlugChapterRoute = ObraSlugChapterRouteImport.update({
  id: '/obra/$slug/$chapter',
  path: '/obra/$slug/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/ranking': typeof RankingRoute
  '/ranking-leitores': typeof RankingLeitoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/listas/$id': typeof ListasIdRoute
  '/u/$username': typeof UUsernameRoute
  '/listas/': typeof ListasIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/contas': typeof AuthenticatedAdminContasRoute
  '/admin/molduras': typeof AuthenticatedAdminMoldurasRoute
  '/admin/nova': typeof AuthenticatedAdminNovaRoute
  '/admin/novels': typeof AuthenticatedAdminNovelsRoute
  '/admin/obras': typeof AuthenticatedAdminObrasRoute
  '/admin/selos': typeof AuthenticatedAdminSelosRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/obra/$slug/$chapter': typeof ObraSlugChapterRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/obra/$slug/': typeof ObraSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/ranking': typeof RankingRoute
  '/ranking-leitores': typeof RankingLeitoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/listas/$id': typeof ListasIdRoute
  '/u/$username': typeof UUsernameRoute
  '/listas': typeof ListasIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/contas': typeof AuthenticatedAdminContasRoute
  '/admin/molduras': typeof AuthenticatedAdminMoldurasRoute
  '/admin/nova': typeof AuthenticatedAdminNovaRoute
  '/admin/novels': typeof AuthenticatedAdminNovelsRoute
  '/admin/obras': typeof AuthenticatedAdminObrasRoute
  '/admin/selos': typeof AuthenticatedAdminSelosRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/obra/$slug/$chapter': typeof ObraSlugChapterRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/obra/$slug': typeof ObraSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/ranking': typeof RankingRoute
  '/ranking-leitores': typeof RankingLeitoresRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/listas/$id': typeof ListasIdRoute
  '/u/$username': typeof UUsernameRoute
  '/listas/': typeof ListasIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/contas': typeof AuthenticatedAdminContasRoute
  '/_authenticated/admin/molduras': typeof AuthenticatedAdminMoldurasRoute
  '/_authenticated/admin/nova': typeof AuthenticatedAdminNovaRoute
  '/_authenticated/admin/novels': typeof AuthenticatedAdminNovelsRoute
  '/_authenticated/admin/obras': typeof AuthenticatedAdminObrasRoute
  '/_authenticated/admin/selos': typeof AuthenticatedAdminSelosRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/obra/$slug/$chapter': typeof ObraSlugChapterRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/obra/$slug/': typeof ObraSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/ranking'
    | '/ranking-leitores'
    | '/sitemap.xml'
    | '/biblioteca'
    | '/historico'
    | '/listas/$id'
    | '/u/$username'
    | '/listas/'
    | '/admin/$id'
    | '/admin/contas'
    | '/admin/molduras'
    | '/admin/nova'
    | '/admin/novels'
    | '/admin/obras'
    | '/admin/selos'
    | '/admin/suporte'
    | '/obra/$slug/$chapter'
    | '/admin/'
    | '/obra/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/ranking'
    | '/ranking-leitores'
    | '/sitemap.xml'
    | '/biblioteca'
    | '/historico'
    | '/listas/$id'
    | '/u/$username'
    | '/listas'
    | '/admin/$id'
    | '/admin/contas'
    | '/admin/molduras'
    | '/admin/nova'
    | '/admin/novels'
    | '/admin/obras'
    | '/admin/selos'
    | '/admin/suporte'
    | '/obra/$slug/$chapter'
    | '/admin'
    | '/obra/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalogo'
    | '/ranking'
    | '/ranking-leitores'
    | '/sitemap.xml'
    | '/_authenticated/biblioteca'
    | '/_authenticated/historico'
    | '/listas/$id'
    | '/u/$username'
    | '/listas/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/contas'
    | '/_authenticated/admin/molduras'
    | '/_authenticated/admin/nova'
    | '/_authenticated/admin/novels'
    | '/_authenticated/admin/obras'
    | '/_authenticated/admin/selos'
    | '/_authenticated/admin/suporte'
    | '/obra/$slug/$chapter'
    | '/_authenticated/admin/'
    | '/obra/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRoute
  RankingRoute: typeof RankingRoute
  RankingLeitoresRoute: typeof RankingLeitoresRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ListasIdRoute: typeof ListasIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ListasIndexRoute: typeof ListasIndexRoute
  ObraSlugChapterRoute: typeof ObraSlugChapterRoute
  ObraSlugIndexRoute: typeof ObraSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-leitores': {
      id: '/ranking-leitores'
      path: '/ranking-leitores'
      fullPath: '/ranking-leitores'
      preLoaderRoute: typeof RankingLeitoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/listas/': {
      id: '/listas/'
      path: '/listas'
      fullPath: '/listas/'
      preLoaderRoute: typeof ListasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas/$id': {
      id: '/listas/$id'
      path: '/listas/$id'
      fullPath: '/listas/$id'
      preLoaderRoute: typeof ListasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contas': {
      id: '/_authenticated/admin/contas'
      path: '/admin/contas'
      fullPath: '/admin/contas'
      preLoaderRoute: typeof AuthenticatedAdminContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/molduras': {
      id: '/_authenticated/admin/molduras'
      path: '/admin/molduras'
      fullPath: '/admin/molduras'
      preLoaderRoute: typeof AuthenticatedAdminMoldurasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/nova': {
      id: '/_authenticated/admin/nova'
      path: '/admin/nova'
      fullPath: '/admin/nova'
      preLoaderRoute: typeof AuthenticatedAdminNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/novels': {
      id: '/_authenticated/admin/novels'
      path: '/admin/novels'
      fullPath: '/admin/novels'
      preLoaderRoute: typeof AuthenticatedAdminNovelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/obras': {
      id: '/_authenticated/admin/obras'
      path: '/admin/obras'
      fullPath: '/admin/obras'
      preLoaderRoute: typeof AuthenticatedAdminObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/selos': {
      id: '/_authenticated/admin/selos'
      path: '/admin/selos'
      fullPath: '/admin/selos'
      preLoaderRoute: typeof AuthenticatedAdminSelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/admin/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/obra/$slug/': {
      id: '/obra/$slug/'
      path: '/obra/$slug'
      fullPath: '/obra/$slug/'
      preLoaderRoute: typeof ObraSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$slug/$chapter': {
      id: '/obra/$slug/$chapter'
      path: '/obra/$slug/$chapter'
      fullPath: '/obra/$slug/$chapter'
      preLoaderRoute: typeof ObraSlugChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminContasRoute: typeof AuthenticatedAdminContasRoute
  AuthenticatedAdminMoldurasRoute: typeof AuthenticatedAdminMoldurasRoute
  AuthenticatedAdminNovaRoute: typeof AuthenticatedAdminNovaRoute
  AuthenticatedAdminNovelsRoute: typeof AuthenticatedAdminNovelsRoute
  AuthenticatedAdminObrasRoute: typeof AuthenticatedAdminObrasRoute
  AuthenticatedAdminSelosRoute: typeof AuthenticatedAdminSelosRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminContasRoute: AuthenticatedAdminContasRoute,
  AuthenticatedAdminMoldurasRoute: AuthenticatedAdminMoldurasRoute,
  AuthenticatedAdminNovaRoute: AuthenticatedAdminNovaRoute,
  AuthenticatedAdminNovelsRoute: AuthenticatedAdminNovelsRoute,
  AuthenticatedAdminObrasRoute: AuthenticatedAdminObrasRoute,
  AuthenticatedAdminSelosRoute: AuthenticatedAdminSelosRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRoute,
  RankingRoute: RankingRoute,
  RankingLeitoresRoute: RankingLeitoresRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ListasIdRoute: ListasIdRoute,
  UUsernameRoute: UUsernameRoute,
  ListasIndexRoute: ListasIndexRoute,
  ObraSlugChapterRoute: ObraSlugChapterRoute,
  ObraSlugIndexRoute: ObraSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
